apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: {{ .Values.namespace | default "k8s-microservices" }}
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/managed-by: Helm
data:
  DATABASE_HOST: {{ .Values.config.databaseHost | quote }}
  DATABASE_PORT: {{ .Values.config.databasePort | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}

