apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: k8s-microservices
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "microservices_db"
  JWT_SECRET: "random-secret-key"