apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: k8s-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
  - port: 3000
    targetPort: 3000
