apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: {{ .Values.namespace | default "k8s-microservices" }}
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/managed-by: Helm
data:
  DATABASE_HOST: {{ .Values.config.databaseHost | quote }}
  DATABASE_PORT: {{ .Values.config.databasePort | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}

