apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Values.namespace | default "k8s-microservices" }}
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: product-service
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP

