apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.namespace | default "k8s-microservices" }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/managed-by: Helm
data:
  NEXT_PUBLIC_API_URL: {{ .Values.config.apiUrl | quote }}

