apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace | default "k8s-microservices" }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http

